Заметки numpy (массивы и действия с ними)

In [1]:
#Импорты
import numpy as np

In [2]:
#одномерный массив
arr1=np.array([1,2,3])
print(arr1)
arr1[2]=5
arr1
#одномерный массив с числами от 0 до 20 с шагом в 2(элементов сколько поместиться до границы(невключительно))
arrR=np.arange(0,20,2)
#одномерный массив из 20 вещественных чисел от 0 до 10(включительно оба)
arrL=np.linspace(0,10,20)
#одномерный массив из 4 целых чисел от -10 до 10 
arrInt=np.random.randint(-10,10,4)

[1 2 3]


In [3]:
#двумерный массив 2 строки, 3 столбца
arr2=np.array([[1,2,3],[4,5,6]])

#Размерность массива (Строки х Столбцы)
#print("Размер массива",arr2.shape)

#Колво измерений массива
#print("Колво измерений массива",arr2.ndim)

#Заменить всю вторую строку 5-ками
arr2[1]=5
#последний элемент 1 строки(arr2[0,2])
print(arr2[0,-1])


#Двумерные массивы из нулей/единиц размером 10х10
#print(np.zeros((10,10)))
#print(np.ones((10,10)))

#Двумерный массив размера 4х4 с единицами по диагонали
#print(np.eye(4))

#Двумерный массив размера 5х5(колво переданных чисел) с заданными числами по диагонали
#Если в функцию передать двумерный массив, то получим массив из его диагональных чисел
#print(np.diag([1,2,3,4,5]))

# двумерный массив 3x4 вещественных чисел от 0 до 1
arrNM=np.random.rand(5,5)

#0 - sum,min,max,median,mean всех значений столбца / 1 - sum,min,max,median,mean всех значений строки
#print(arr2)
#np.median(arr2,axis=1)
arrNM

3


array([[0.84990486, 0.27161719, 0.76491534, 0.43537609, 0.1635552 ],
       [0.79841999, 0.53369923, 0.39579462, 0.81020079, 0.3074273 ],
       [0.80354744, 0.83586103, 0.69982723, 0.67309217, 0.5339936 ],
       [0.05566355, 0.51267182, 0.82044432, 0.01437323, 0.45464859],
       [0.99465759, 0.52074325, 0.78742883, 0.02312438, 0.02353715]])

In [4]:
#slice одномерного массива
arr = np.array([1, 2, 3, 4, 5, 6, 7])
#от 4 элемента(включительно) до конца
print(arr[4:]) 
#от начала до 4 элемента(невключительно)
print(arr[:4]) 
#от 1(включительно) до 5 элемента(невключительно)
print(arr[1:5]) 
#от 3(невключительно) с обратной стороны и до конца
print(arr[-3:])
#от 1(включительно) до 5 элемента(невключительно) с шагом 2
print(arr[1:5:2]) 
#шаг 3 
print(arr[::2]) 

[5 6 7]
[1 2 3 4]
[2 3 4 5]
[5 6 7]
[2 4]
[1 3 5 7]


In [5]:
#slice двумерного массива
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
#print(arr)
#во второй строке элементы от 1 до 4(невключительно)
#print(arr[1, 1:4])

#От двух строк возвращаем 2 элемент(получается одномерный массив)
print(arr[0:2, 2])
#От второй строки до конца возвращаем 2 элемент(получается двумерный массив)
#P.S. массив см пред пункт
print(arrNM[1:,2:3])


#От двух строк возвращаем  элементы от 1 до 4(невключительно)
#print(arr[0:2, 1:4])


[3 8]
[[0.39579462]
 [0.69982723]
 [0.82044432]
 [0.78742883]]


In [6]:
#изменение массивов
#добавление
arr=np.array([1,2,3,4,5])
#массив,индекс,подмассив
arr=np.insert(arr,5,[6,7,8,9])
#добавляет в конец
arr=np.append(arr,0)
#удаление
#массив,подмассив индексов или один индекс
arr=np.delete(arr,[1,3])
#объединение
arr1=np.array([[1,2,3],[1,2,3]])
arr2=np.array([[4,5,6],[4,5,6]])
#массив1, массив2, 0/1 - второй массив добавляется как новые строки/столбцы
#np.vstack как 0, hstack как 1 
arr12=np.concatenate((arr1,arr2),axis=1)
arr12

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [7]:
#Уникальные числа
arr=np.array([1,1,1,2,2,2,3,3,3,3])
#Массив уникальных чисел
np.unique(arr)
#число,кол-во вхождений
uniques,counts=np.unique(arr,return_counts=True)
#сопоставляем
#for i in range(0,len(uniques)):
#    uniqcount[uniques[i]]=counts[i]
#uniqcount

#Операции как с множествами
arr1=np.array([[1,2,3,4,5]])
arr2=np.array([[3,4,5,6,7]])
#Пересечение (элементы которые есть в обоих массивах)
print(np.intersect1d(arr1,arr2))
#Объединение (элементы из обоих массивов без повтора)
print(np.union1d(arr1,arr2))
#Разность (элементы из первого переданного массива которых нет во втором)
print(np.setdiff1d(arr2,arr1))
#Разность (элементы из которых нет во втором но есть в первом и которые есть во втором но нет в первом)
print(np.setxor1d(arr1,arr2))

[3 4 5]
[1 2 3 4 5 6 7]
[6 7]
[1 2 6 7]
